[
    ImplementedAs=window_modules_constructors
] partial interface Window {
    [OriginTrialEnabled=AnimationWorklet] attribute WorkletAnimationConstructor WorkletAnimation;
    [OriginTrialEnabled=BudgetQuery] attribute BudgetStateConstructor BudgetState;
    [OriginTrialEnabled=CookieStore, SecureContext] attribute CookieChangeEventConstructor CookieChangeEvent;
    [OriginTrialEnabled=CookieStore, SecureContext] attribute CookieStoreConstructor CookieStore;
    [OriginTrialEnabled=MediaCapabilities] attribute MediaCapabilitiesInfoConstructor MediaCapabilitiesInfo;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRConstructor XR;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRCoordinateSystemConstructor XRCoordinateSystem;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRDeviceConstructor XRDevice;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRDevicePoseConstructor XRDevicePose;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRFrameConstructor XRFrame;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRFrameOfReferenceConstructor XRFrameOfReference;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRInputPoseConstructor XRInputPose;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRInputSourceConstructor XRInputSource;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRInputSourceEventConstructor XRInputSourceEvent;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRLayerConstructor XRLayer;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRPresentationContextConstructor XRPresentationContext;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRRayConstructor XRRay;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRSessionConstructor XRSession;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRSessionEventConstructor XRSessionEvent;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRStageBoundsConstructor XRStageBounds;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRStageBoundsPointConstructor XRStageBoundsPoint;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRViewConstructor XRView;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRViewportConstructor XRViewport;
    [OriginTrialEnabled=WebXR, SecureContext] attribute XRWebGLLayerConstructor XRWebGLLayer;
    [RuntimeEnabled=BackgroundFetch] attribute BackgroundFetchFetchConstructor BackgroundFetchFetch;
    [RuntimeEnabled=BackgroundFetch] attribute BackgroundFetchManagerConstructor BackgroundFetchManager;
    [RuntimeEnabled=BackgroundFetch] attribute BackgroundFetchRegistrationConstructor BackgroundFetchRegistration;
    [RuntimeEnabled=Budget, SecureContext] attribute BudgetServiceConstructor BudgetService;
    [RuntimeEnabled=GamepadExtensions] attribute GamepadPoseConstructor GamepadPose;
    [RuntimeEnabled=GamepadVibration] attribute GamepadHapticActuatorConstructor GamepadHapticActuator;
    [RuntimeEnabled=IDBObserver] attribute IDBObservationConstructor IDBObservation;
    [RuntimeEnabled=IDBObserver] attribute IDBObserverChangesConstructor IDBObserverChanges;
    [RuntimeEnabled=IDBObserver] attribute IDBObserverConstructor IDBObserver;
    [RuntimeEnabled=KeyboardMap, SecureContext] attribute KeyboardLayoutMapConstructor KeyboardLayoutMap;
    [RuntimeEnabled=MediaSession] attribute MediaMetadataConstructor MediaMetadata;
    [RuntimeEnabled=MediaSession] attribute MediaSessionConstructor MediaSession;
    [RuntimeEnabled=MediaSourceExperimental] attribute TrackDefaultConstructor TrackDefault;
    [RuntimeEnabled=MediaSourceExperimental] attribute TrackDefaultListConstructor TrackDefaultList;
    [RuntimeEnabled=MediaSourceExperimental] attribute VideoPlaybackQualityConstructor VideoPlaybackQuality;
    [RuntimeEnabled=Notifications] attribute NotificationConstructor Notification;
    [RuntimeEnabled=OffscreenCanvas] attribute OffscreenCanvasRenderingContext2DConstructor OffscreenCanvasRenderingContext2D;
    [RuntimeEnabled=PaymentApp] attribute PaymentInstrumentsConstructor PaymentInstruments;
    [RuntimeEnabled=PaymentApp] attribute PaymentManagerConstructor PaymentManager;
    [RuntimeEnabled=PaymentRequest, SecureContext] attribute PaymentAddressConstructor PaymentAddress;
    [RuntimeEnabled=PaymentRequest, SecureContext] attribute PaymentRequestConstructor PaymentRequest;
    [RuntimeEnabled=PaymentRequest, SecureContext] attribute PaymentResponseConstructor PaymentResponse;
    [RuntimeEnabled=PaymentRequest] attribute PaymentRequestUpdateEventConstructor PaymentRequestUpdateEvent;
    [RuntimeEnabled=Permissions] attribute PermissionStatusConstructor PermissionStatus;
    [RuntimeEnabled=Permissions] attribute PermissionsConstructor Permissions;
    [RuntimeEnabled=PictureInPictureAPI] attribute PictureInPictureWindowConstructor PictureInPictureWindow;
    [RuntimeEnabled=Presentation] attribute PresentationAvailabilityConstructor PresentationAvailability;
    [RuntimeEnabled=Presentation] attribute PresentationConnectionAvailableEventConstructor PresentationConnectionAvailableEvent;
    [RuntimeEnabled=Presentation] attribute PresentationConnectionCloseEventConstructor PresentationConnectionCloseEvent;
    [RuntimeEnabled=Presentation] attribute PresentationConnectionConstructor PresentationConnection;
    [RuntimeEnabled=Presentation] attribute PresentationConnectionListConstructor PresentationConnectionList;
    [RuntimeEnabled=Presentation] attribute PresentationConstructor Presentation;
    [RuntimeEnabled=Presentation] attribute PresentationReceiverConstructor PresentationReceiver;
    [RuntimeEnabled=Presentation] attribute PresentationRequestConstructor PresentationRequest;
    [RuntimeEnabled=PushMessaging] attribute PushManagerConstructor PushManager;
    [RuntimeEnabled=PushMessaging] attribute PushSubscriptionConstructor PushSubscription;
    [RuntimeEnabled=PushMessaging] attribute PushSubscriptionOptionsConstructor PushSubscriptionOptions;
    [RuntimeEnabled=RemotePlayback] attribute RemotePlaybackConstructor RemotePlayback;
    [RuntimeEnabled=ScriptedSpeech] attribute SpeechSynthesisEventConstructor SpeechSynthesisEvent;
    [RuntimeEnabled=ScriptedSpeech] attribute SpeechSynthesisUtteranceConstructor SpeechSynthesisUtterance;
    [RuntimeEnabled=Sensor, SecureContext] attribute AbsoluteOrientationSensorConstructor AbsoluteOrientationSensor;
    [RuntimeEnabled=Sensor, SecureContext] attribute AccelerometerConstructor Accelerometer;
    [RuntimeEnabled=Sensor, SecureContext] attribute GyroscopeConstructor Gyroscope;
    [RuntimeEnabled=Sensor, SecureContext] attribute LinearAccelerationSensorConstructor LinearAccelerationSensor;
    [RuntimeEnabled=Sensor, SecureContext] attribute OrientationSensorConstructor OrientationSensor;
    [RuntimeEnabled=Sensor, SecureContext] attribute RelativeOrientationSensorConstructor RelativeOrientationSensor;
    [RuntimeEnabled=Sensor, SecureContext] attribute SensorConstructor Sensor;
    [RuntimeEnabled=Sensor, SecureContext] attribute SensorErrorEventConstructor SensorErrorEvent;
    [RuntimeEnabled=SensorExtraClasses, SecureContext] attribute AmbientLightSensorConstructor AmbientLightSensor;
    [RuntimeEnabled=SensorExtraClasses, SecureContext] attribute MagnetometerConstructor Magnetometer;
    [RuntimeEnabled=ShapeDetection] attribute BarcodeDetectorConstructor BarcodeDetector;
    [RuntimeEnabled=ShapeDetection] attribute DetectedBarcodeConstructor DetectedBarcode;
    [RuntimeEnabled=ShapeDetection] attribute DetectedFaceConstructor DetectedFace;
    [RuntimeEnabled=ShapeDetection] attribute DetectedTextConstructor DetectedText;
    [RuntimeEnabled=ShapeDetection] attribute FaceDetectorConstructor FaceDetector;
    [RuntimeEnabled=ShapeDetection] attribute TextDetectorConstructor TextDetector;
    [RuntimeEnabled=StableBlinkFeatures] attribute CanvasGradientConstructor CanvasGradient;
    [RuntimeEnabled=StableBlinkFeatures] attribute CanvasPatternConstructor CanvasPattern;
    [RuntimeEnabled=StableBlinkFeatures] attribute Path2DConstructor Path2D;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGL2ComputeRenderingContextConstructor WebGL2ComputeRenderingContext;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGL2RenderingContextConstructor WebGL2RenderingContext;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLActiveInfoConstructor WebGLActiveInfo;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLBufferConstructor WebGLBuffer;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLFramebufferConstructor WebGLFramebuffer;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLProgramConstructor WebGLProgram;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLQueryConstructor WebGLQuery;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLRenderbufferConstructor WebGLRenderbuffer;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLRenderingContextConstructor WebGLRenderingContext;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLSamplerConstructor WebGLSampler;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLShaderConstructor WebGLShader;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLShaderPrecisionFormatConstructor WebGLShaderPrecisionFormat;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLSyncConstructor WebGLSync;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLTextureConstructor WebGLTexture;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLTransformFeedbackConstructor WebGLTransformFeedback;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLUniformLocationConstructor WebGLUniformLocation;
    [RuntimeEnabled=StableBlinkFeatures] attribute WebGLVertexArrayObjectConstructor WebGLVertexArrayObject;
    [RuntimeEnabled=WebAuth, SecureContext] attribute AuthenticatorAssertionResponseConstructor AuthenticatorAssertionResponse;
    [RuntimeEnabled=WebAuth, SecureContext] attribute AuthenticatorAttestationResponseConstructor AuthenticatorAttestationResponse;
    [RuntimeEnabled=WebAuth, SecureContext] attribute AuthenticatorResponseConstructor AuthenticatorResponse;
    [RuntimeEnabled=WebAuth, SecureContext] attribute PublicKeyCredentialConstructor PublicKeyCredential;
    [RuntimeEnabled=WebBluetooth, SecureContext] attribute BluetoothCharacteristicPropertiesConstructor BluetoothCharacteristicProperties;
    [RuntimeEnabled=WebBluetooth, SecureContext] attribute BluetoothConstructor Bluetooth;
    [RuntimeEnabled=WebBluetooth, SecureContext] attribute BluetoothDeviceConstructor BluetoothDevice;
    [RuntimeEnabled=WebBluetooth, SecureContext] attribute BluetoothRemoteGATTCharacteristicConstructor BluetoothRemoteGATTCharacteristic;
    [RuntimeEnabled=WebBluetooth, SecureContext] attribute BluetoothRemoteGATTDescriptorConstructor BluetoothRemoteGATTDescriptor;
    [RuntimeEnabled=WebBluetooth, SecureContext] attribute BluetoothRemoteGATTServerConstructor BluetoothRemoteGATTServer;
    [RuntimeEnabled=WebBluetooth, SecureContext] attribute BluetoothRemoteGATTServiceConstructor BluetoothRemoteGATTService;
    [RuntimeEnabled=WebBluetooth] attribute BluetoothUUIDConstructor BluetoothUUID;
    [RuntimeEnabled=WebGPU] attribute WebGPUAdapterConstructor WebGPUAdapter;
    [RuntimeEnabled=WebGPU] attribute WebGPUConstructor WebGPU;
    [RuntimeEnabled=WebGPU] attribute WebGPUDeviceConstructor WebGPUDevice;
    [RuntimeEnabled=WebLocksAPI, SecureContext] attribute LockConstructor Lock;
    [RuntimeEnabled=WebLocksAPI, SecureContext] attribute LockManagerConstructor LockManager;
    [RuntimeEnabled=WebNFC, SecureContext] attribute NFCConstructor NFC;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBAlternateInterfaceConstructor USBAlternateInterface;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBConfigurationConstructor USBConfiguration;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBConnectionEventConstructor USBConnectionEvent;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBConstructor USB;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBDeviceConstructor USBDevice;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBEndpointConstructor USBEndpoint;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBInTransferResultConstructor USBInTransferResult;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBInterfaceConstructor USBInterface;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBIsochronousInTransferPacketConstructor USBIsochronousInTransferPacket;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBIsochronousInTransferResultConstructor USBIsochronousInTransferResult;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBIsochronousOutTransferPacketConstructor USBIsochronousOutTransferPacket;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBIsochronousOutTransferResultConstructor USBIsochronousOutTransferResult;
    [RuntimeEnabled=WebUSB, SecureContext] attribute USBOutTransferResultConstructor USBOutTransferResult;
    [RuntimeEnabled=WebVR] attribute VRDisplayCapabilitiesConstructor VRDisplayCapabilities;
    [RuntimeEnabled=WebVR] attribute VRDisplayConstructor VRDisplay;
    [RuntimeEnabled=WebVR] attribute VRDisplayEventConstructor VRDisplayEvent;
    [RuntimeEnabled=WebVR] attribute VREyeParametersConstructor VREyeParameters;
    [RuntimeEnabled=WebVR] attribute VRFrameDataConstructor VRFrameData;
    [RuntimeEnabled=WebVR] attribute VRPoseConstructor VRPose;
    [RuntimeEnabled=WebVR] attribute VRStageParametersConstructor VRStageParameters;
    [RuntimeEnabled=WebXRHitTest, SecureContext] attribute XRHitResultConstructor XRHitResult;
    [SecureContext] attribute AudioWorkletConstructor AudioWorklet;
    [SecureContext] attribute CacheConstructor Cache;
    [SecureContext] attribute CacheStorageConstructor CacheStorage;
    [SecureContext] attribute ClipboardConstructor Clipboard;
    [SecureContext] attribute CredentialConstructor Credential;
    [SecureContext] attribute CredentialsContainerConstructor CredentialsContainer;
    [SecureContext] attribute FederatedCredentialConstructor FederatedCredential;
    [SecureContext] attribute KeyboardConstructor Keyboard;
    [SecureContext] attribute MediaKeyMessageEventConstructor MediaKeyMessageEvent;
    [SecureContext] attribute MediaKeySessionConstructor MediaKeySession;
    [SecureContext] attribute MediaKeyStatusMapConstructor MediaKeyStatusMap;
    [SecureContext] attribute MediaKeySystemAccessConstructor MediaKeySystemAccess;
    [SecureContext] attribute MediaKeysConstructor MediaKeys;
    [SecureContext] attribute NavigationPreloadManagerConstructor NavigationPreloadManager;
    [SecureContext] attribute PasswordCredentialConstructor PasswordCredential;
    [SecureContext] attribute ServiceWorkerConstructor ServiceWorker;
    [SecureContext] attribute ServiceWorkerContainerConstructor ServiceWorkerContainer;
    [SecureContext] attribute ServiceWorkerRegistrationConstructor ServiceWorkerRegistration;
    [SecureContext] attribute StorageManagerConstructor StorageManager;
    attribute AnalyserNodeConstructor AnalyserNode;
    attribute AudioBufferConstructor AudioBuffer;
    attribute AudioBufferSourceNodeConstructor AudioBufferSourceNode;
    attribute AudioContextConstructor AudioContext;
    attribute AudioDestinationNodeConstructor AudioDestinationNode;
    attribute AudioListenerConstructor AudioListener;
    attribute AudioNodeConstructor AudioNode;
    attribute AudioParamConstructor AudioParam;
    attribute AudioParamMapConstructor AudioParamMap;
    attribute AudioProcessingEventConstructor AudioProcessingEvent;
    attribute AudioScheduledSourceNodeConstructor AudioScheduledSourceNode;
    attribute AudioWorkletNodeConstructor AudioWorkletNode;
    attribute BaseAudioContextConstructor BaseAudioContext;
    attribute BatteryManagerConstructor BatteryManager;
    attribute BeforeInstallPromptEventConstructor BeforeInstallPromptEvent;
    attribute BiquadFilterNodeConstructor BiquadFilterNode;
    attribute BlobEventConstructor BlobEvent;
    attribute BroadcastChannelConstructor BroadcastChannel;
    attribute CanvasCaptureMediaStreamTrackConstructor CanvasCaptureMediaStreamTrack;
    attribute CanvasRenderingContext2DConstructor CanvasRenderingContext2D;
    attribute ChannelMergerNodeConstructor ChannelMergerNode;
    attribute ChannelSplitterNodeConstructor ChannelSplitterNode;
    attribute CloseEventConstructor CloseEvent;
    attribute ConstantSourceNodeConstructor ConstantSourceNode;
    attribute ConvolverNodeConstructor ConvolverNode;
    attribute CryptoConstructor Crypto;
    attribute CryptoKeyConstructor CryptoKey;
    attribute DOMErrorConstructor DOMError;
    attribute DelayNodeConstructor DelayNode;
    attribute DeviceMotionEventConstructor DeviceMotionEvent;
    attribute DeviceOrientationEventConstructor DeviceOrientationEvent;
    attribute DynamicsCompressorNodeConstructor DynamicsCompressorNode;
    attribute EventSourceConstructor EventSource;
    attribute GainNodeConstructor GainNode;
    attribute GamepadButtonConstructor GamepadButton;
    attribute GamepadConstructor Gamepad;
    attribute GamepadEventConstructor GamepadEvent;
    attribute IDBCursorConstructor IDBCursor;
    attribute IDBCursorWithValueConstructor IDBCursorWithValue;
    attribute IDBDatabaseConstructor IDBDatabase;
    attribute IDBFactoryConstructor IDBFactory;
    attribute IDBIndexConstructor IDBIndex;
    attribute IDBKeyRangeConstructor IDBKeyRange;
    attribute IDBObjectStoreConstructor IDBObjectStore;
    attribute IDBOpenDBRequestConstructor IDBOpenDBRequest;
    attribute IDBRequestConstructor IDBRequest;
    attribute IDBTransactionConstructor IDBTransaction;
    attribute IDBVersionChangeEventConstructor IDBVersionChangeEvent;
    attribute IIRFilterNodeConstructor IIRFilterNode;
    attribute IPCFuzzerConstructor IPCFuzzer;
    attribute ImageBitmapRenderingContextConstructor ImageBitmapRenderingContext;
    attribute ImageCaptureConstructor ImageCapture;
    attribute InputDeviceInfoConstructor InputDeviceInfo;
    attribute MIDIAccessConstructor MIDIAccess;
    attribute MIDIConnectionEventConstructor MIDIConnectionEvent;
    attribute MIDIInputConstructor MIDIInput;
    attribute MIDIInputMapConstructor MIDIInputMap;
    attribute MIDIMessageEventConstructor MIDIMessageEvent;
    attribute MIDIOutputConstructor MIDIOutput;
    attribute MIDIOutputMapConstructor MIDIOutputMap;
    attribute MIDIPortConstructor MIDIPort;
    attribute MediaCapabilitiesConstructor MediaCapabilities;
    attribute MediaDeviceInfoConstructor MediaDeviceInfo;
    attribute MediaDevicesConstructor MediaDevices;
    attribute MediaElementAudioSourceNodeConstructor MediaElementAudioSourceNode;
    attribute MediaEncryptedEventConstructor MediaEncryptedEvent;
    attribute MediaRecorderConstructor MediaRecorder;
    attribute MediaSettingsRangeConstructor MediaSettingsRange;
    attribute MediaSourceConstructor MediaSource;
    attribute MediaStreamAudioDestinationNodeConstructor MediaStreamAudioDestinationNode;
    attribute MediaStreamAudioSourceNodeConstructor MediaStreamAudioSourceNode;
    attribute MediaStreamConstructor MediaStream;
    attribute MediaStreamEventConstructor MediaStreamEvent;
    attribute MediaStreamTrackConstructor MediaStreamTrack;
    attribute MediaStreamTrackEventConstructor MediaStreamTrackEvent;
    attribute MimeTypeArrayConstructor MimeTypeArray;
    attribute MimeTypeConstructor MimeType;
    attribute NetworkInformationConstructor NetworkInformation;
    attribute OfflineAudioCompletionEventConstructor OfflineAudioCompletionEvent;
    attribute OfflineAudioContextConstructor OfflineAudioContext;
    attribute OscillatorNodeConstructor OscillatorNode;
    attribute OverconstrainedErrorConstructor OverconstrainedError;
    attribute PannerNodeConstructor PannerNode;
    attribute PeriodicWaveConstructor PeriodicWave;
    attribute PhotoCapabilitiesConstructor PhotoCapabilities;
    attribute PluginArrayConstructor PluginArray;
    attribute PluginConstructor Plugin;
    attribute RTCCertificateConstructor RTCCertificate;
    attribute RTCDTMFSenderConstructor RTCDTMFSender;
    attribute RTCDTMFToneChangeEventConstructor RTCDTMFToneChangeEvent;
    attribute RTCDataChannelConstructor RTCDataChannel;
    attribute RTCDataChannelEventConstructor RTCDataChannelEvent;
    attribute RTCIceCandidateConstructor RTCIceCandidate;
    attribute RTCPeerConnectionConstructor RTCPeerConnection;
    attribute RTCPeerConnectionIceEventConstructor RTCPeerConnectionIceEvent;
    attribute RTCRtpContributingSourceConstructor RTCRtpContributingSource;
    attribute RTCRtpReceiverConstructor RTCRtpReceiver;
    attribute RTCRtpSenderConstructor RTCRtpSender;
    attribute RTCRtpTransceiverConstructor RTCRtpTransceiver;
    attribute RTCSessionDescriptionConstructor RTCSessionDescription;
    attribute RTCStatsReportConstructor RTCStatsReport;
    attribute RTCTrackEventConstructor RTCTrackEvent;
    attribute ScreenOrientationConstructor ScreenOrientation;
    attribute ScriptProcessorNodeConstructor ScriptProcessorNode;
    attribute SourceBufferConstructor SourceBuffer;
    attribute SourceBufferListConstructor SourceBufferList;
    attribute StereoPannerNodeConstructor StereoPannerNode;
    attribute StorageConstructor Storage;
    attribute StorageEventConstructor StorageEvent;
    attribute SubtleCryptoConstructor SubtleCrypto;
    attribute SyncManagerConstructor SyncManager;
    attribute TextDecoderConstructor TextDecoder;
    attribute TextEncoderConstructor TextEncoder;
    attribute WaveShaperNodeConstructor WaveShaperNode;
    attribute WebGLContextEventConstructor WebGLContextEvent;
    attribute WebSocketConstructor WebSocket;
};
