"""Maps the WebIDL interfaces of HTML elements to their respective tags"""

# abstract classes: HTMLElement, HTMLMediaElement, HTMLModElement, HTMLQuoteElement

WEBIDL_TO_TAG: dict[str, str] = {
    "HTMLAnchorElement": "a",
    "HTMLAreaElement": "area",
    "HTMLAudioElement": "audio",
    "HTMLBaseElement": "base",
    "HTMLBodyElement": "body",
    "HTMLBRElement": "br",
    "HTMLButtonElement": "button",
    "HTMLCanvasElement": "canvas",
    "HTMLDataElement": "data",
    "HTMLDataListElement": "datalist",
    "HTMLDetailsElement": "details",
    "HTMLDialogElement": "dialog",
    "HTMLDirectoryElement": "dir",
    "HTMLDivElement": "div",
    "HTMLDListElement": "dl",
    "HTMLEmbedElement": "embed",
    "HTMLFencedFrameElement": "fencedframe",  # Chrome
    "HTMLFieldSetElement": "fieldset",
    "HTMLFontElement": "font",
    "HTMLFormElement": "form",
    "HTMLFrameElement": "frame",
    "HTMLFrameSetElement": "frameset",
    "HTMLHeadElement": "head",
    "HTMLHeadingElement": "h1",
    "HTMLHRElement": "hr",
    "HTMLHtmlElement": "html",
    "HTMLIFrameElement": "iframe",
    "HTMLImageElement": "img",
    "HTMLInputElement": "input",
    "HTMLLabelElement": "label",
    "HTMLLegendElement": "legend",
    "HTMLLIElement": "li",
    "HTMLLinkElement": "link",
    "HTMLMapElement": "map",
    "HTMLMarqueeElement": "marquee",
    "HTMLMenuElement": "menu",
    "HTMLMetaElement": "meta",
    "HTMLMeterElement": "meter",
    "HTMLObjectElement": "object",
    "HTMLOListElement": "ol",
    "HTMLOptGroupElement": "optgroup",
    "HTMLOptionElement": "option",
    "HTMLOutputElement": "output",
    "HTMLParagraphElement": "p",
    "HTMLParamElement": "param",
    "HTMLPermissionElement": "permission",  # Chrome
    "HTMLPictureElement": "picture",
    "HTMLPreElement": "pre",
    "HTMLProgressElement": "progress",
    "HTMLScriptElement": "script",
    "HTMLSelectElement": "select",
    "HTMLSelectListElement": "selectlist",  # Chrome
    "HTMLSlotElement": "slot",
    "HTMLSourceElement": "source",
    "HTMLSpanElement": "span",
    "HTMLStyleElement": "style",
    "HTMLTableCaptionElement": "caption",
    "HTMLTableCellElement": "td",
    "HTMLTableColElement": "col",
    "HTMLTableElement": "table",
    "HTMLTableRowElement": "tr",
    "HTMLTableSectionElement": "section",
    "HTMLTemplateElement": "template",
    "HTMLTextAreaElement": "textarea",
    "HTMLTimeElement": "time",
    "HTMLTitleElement": "title",
    "HTMLTrackElement": "track",
    "HTMLUListElement": "ul",
    "HTMLVideoElement": "video",
}

TAG_TO_WEBIDL: dict[str, str] = {v: k for k, v in WEBIDL_TO_TAG.items()}

TAG_HIERARCHY: dict[str, list[str]] = {
    "track": ["audio", "video"],
    "source": ["audio", "video", "picture"],
    "param": ["object"],
    "menuitem": ["menu"],
    "frame": ["frameset"],
    "input": ["form"],
    "button": ["form"],
}
